# Server properties
server:
  servlet:
    context-path: /app_web_futbol
  port: 8080

# Spring properties
spring:
  application:
    name: AsoFutbol
  datasource:
    url: jdbc:postgresql://containers-us-west-123.railway.app:7447/railway #jdbc:postgresql://<host>:<puerto>/<nombre de la base de datos>
    username: postgres
    password: NwXcPujqMeitcnCgXjh6
    driverClassName: org.postgresql.Driver